# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: eduardorvieira
# "service" is the name of this project. This will also be added to your AWS resource names.
service: Medical-Clinic

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    PatientTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Patient
        AttributeDefinitions:
          - AttributeName: PK #taxId
            AttributeType: S
        KeySchema:
          - AttributeName: PK #taxId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST